### ISSUE TITLE
Escribir título y abstract

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2014_CS_Journal_URLS#10]
El título y abstract son fundamentales y deben escribirse antes que el resto del trabajo, porque marcan los objetivos y la narrativa del mismo. Deberías empezar por eso antes de continuar con el resto.

**Comment by unintendedbear** [comment]
Si ya, pero desde que yo lo estoy haciendo todo, pero todo, y escribiendo desde cero aún las cosas que no me estaban asignadas, pues no quise asignarme más. Pero lo haré en cuanto pueda :\
